
def explain_attack(attack_type):
    """
    Returns a dictionary containing the explanation for the given attack type.
    """
    explanations = {
        "Normal": {
            "description": "Legitimate network traffic.",
            "happening": "- Standard user activity or background system processes.\n- No malicious patterns detected.",
            "to_do": "- No action required.\n- Continue monitoring as usual.",
            "not_to_do": "- Do not block this traffic or raise alarms."
        },
        "DoS": { # Denial of Service
            "description": "A Denial of Service (DoS) attack attempts to make a machine or network resource unavailable to its intended users.",
            "happening": "- High volume of traffic from a single or few sources.\n- Resource exhaustion (bandwidth, CPU, memory) on the target.",
            "to_do": "- Block the source IP addresses.\n- Implement rate limiting.\n- Analyze traffic logs to identify the specific DoS method (e.g., SYN flood).",
            "not_to_do": "- Do not ignore prolonged high traffic alerts.\n- Do not shut down the server immediately unless necessary to protect hardware."
        },
        "Probe": { # Probing / Port Scanning
            "description": "A Probe attack (or surveillance) involves scanning a network to identify valid IP addresses, open ports, and operating systems.",
            "happening": "- Sequential or random connection attempts to multiple ports.\n- Mapping of network topology and services.",
            "to_do": "- Block the source IP if scanning is aggressive.\n- Review firewall rules to ensure only necessary ports are open.\n- Check for subsequent unauthorized access attempts.",
            "not_to_do": "- Do not expose sensitive services to the public internet unnecessarily."
        },
        "Brute Force": { # Brute Force
             "description": "A Brute Force attack involves repeated attempts to guess credentials (passwords, encryption keys) to gain unauthorized access.",
             "happening": "- Multiple failed login attempts from the same IP or user account.\n- Rapid succession of authentication requests.",
             "to_do": "- Lock the targeted account temporarily.\n- Enforce strong password policies and MFA.\n- Block the source IP after a threshold of failed attempts.",
             "not_to_do": "- Do not allow unlimited login attempts.\n- Do not use weak or default passwords."
        },
        # Fallback for unexpected labels or variations
        "Web Attack": {
             "description": "Attacks targeting web applications (e.g., SQL Injection, XSS).",
             "happening": "- Malicious payloads detected in HTTP requests.\n- Attempts to manipulate database or web page behavior.",
             "to_do": "- Check web server logs.\n- Ensure input validation and WAF are active.",
             "not_to_do": "- Do not ignore WAF alerts."
        },
        "Bot": {
             "description": "Traffic generated by automated bots.",
             "happening": "- Repetitive automated tasks.\n- Potential participation in a botnet.",
             "to_do": "- Verify if the bot is legitimate (e.g., search crawler) or malicious.\n- Block malicious bot user-agents or IPs.",
             "not_to_do": "- Do not whitelist unknown bots."
        },
        "Infiltration": {
             "description": "Internal compromise or backdoor access.",
             "happening": "- Unauthorized access from within the network or via malware.",
             "to_do": "- Isolate the affected host.\n- Scan for malware and rootkits.",
             "not_to_do": "- Do not leave the infected host connected to the network."
        }
    }

    # Normalize input and handle variations
    key = "Unknown"
    for k in explanations:
        if k.lower() in attack_type.lower():
            key = k
            break
            
    if key == "Unknown":
        return {
            "description": f"Detected traffic type: {attack_type}. No specific explanation available.",
            "happening": "- Patterns match a known attack signature but specific details are missing.",
            "to_do": "- Investigate the specific alert details in the NIDS logs.",
            "not_to_do": "- Do not ignore the alert."
        }

    return explanations[key]
